project:
  type: book
  output-dir: docs
  preview:
    browser: true
    port: 3930
    watch-inputs: true

book:
  title: "Numerical Analysis 2018-23"
  author:
    - name: Gustav Delius
      email: gustav.delius@york.ac.uk
      affiliation:
      - name: Department of Mathematics, University of York

  date: today
  license: CC BY-NC-SA
  downloads: pdf
  repo-url: https://github.com/gustavdelius/NumericalAnalysis2018-23/
  repo-branch: main
  repo-actions: edit
  twitter-card: true
  open-graph: true
  sidebar:
    tools:
      - icon: mortarboard-fill
        href: https://maths.york.ac.uk/moodle/course/view.php?id=2528
        text: Moodle page
  chapters:
    - index.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    - chapter06.qmd
    - chapter07.qmd
    - chapter08.qmd
    - chapter09.qmd
    - ivp.qmd
    - bvp.qmd
    - pde.qmd
  appendices:
    - appendix.qmd
    - references.qmd

bibliography: references.bib

filters:
  - pseudocode

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true

link-citations: true

format:
  html:
    theme: cosmo
    link-external-newwindow: true
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
  pdf:
    documentclass: scrreprt
    papersize: a4
    include-before-body:
      text: |
        \numberwithin{algorithm}{chapter}
        \algrenewcommand{\algorithmiccomment}[1]{\hskip3em$\rightarrow$ #1}
    execute:
      echo: false

toc: true
number-sections: true
crossref:
  eq-prefix: Eq.
fig-align: left

execute:
  cache: true
  freeze: auto
